language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox


env:
  matrix:
    secure: S5e+Bft2Hr0ZIsoOcTcVeFAgrIZgL68noQis7g7/z8uPDtRlITdmNJoGV07W1CWVJ/t85h8yGCKBUM2fxB9oaFyAUnKkbHQTRk6nafaZxGeSM0hQPRzzRSzPp/eM3cotZbrJfiPDMn5ig4x4Y3cYUVn8eeoY9OfMCfJ0YNZ9gM7tVa6Sr/lyEjLz4SAwncLNy6BSxbpZ0xnCWv5kk0EHUWHHnwE6SFG+oOxMrueBgnNGJKJlKKFb0SX36CLFbtD7NjT+KWr+FwuU2IV/adCfCdKdt9f+8irxMX2/XF+KLgwPu7WFryMJbtkmMsfdAkNstO3W8V9UrBibS8tMuUDnywxa/EZ3J84RVAbKOLy2Vuusq2sC/Rjz3sC5LXsx5Y6vcwGr+NksF1/xt793Dgzdc1Jbb2fCfP/qgLdDkwHn88uyJIJMpmotjTahW7BU531ETnMcoHwBeH5tIEdITTffXsm9bX76pEeAy7stlZkfgRIGO9XCFcQNa4sDvrmMaaQ/KdvOGD9a6IK8hjk5l+8YTXBzWnij6KKfLDfjn9XCE2M7Pn/D7ke5gyIxejlsxQ7/7qXzzsqEIStykudTNrpxYf3FGMJgpgk4HI1ipHw7OlApd80Ertp4FnaVCmShMZbHaLPIX/Lc1Swiq4p5ff8krwhunjVPiNHsZuWAq3ZwhK8=
