language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
sudo: required
dist: xenial
env:
  matrix:
  - secure: S5e+Bft2Hr0ZIsoOcTcVeFAgrIZgL68noQis7g7/z8uPDtRlITdmNJoGV07W1CWVJ/t85h8yGCKBUM2fxB9oaFyAUnKkbHQTRk6nafaZxGeSM0hQPRzzRSzPp/eM3cotZbrJfiPDMn5ig4x4Y3cYUVn8eeoY9OfMCfJ0YNZ9gM7tVa6Sr/lyEjLz4SAwncLNy6BSxbpZ0xnCWv5kk0EHUWHHnwE6SFG+oOxMrueBgnNGJKJlKKFb0SX36CLFbtD7NjT+KWr+FwuU2IV/adCfCdKdt9f+8irxMX2/XF+KLgwPu7WFryMJbtkmMsfdAkNstO3W8V9UrBibS8tMuUDnywxa/EZ3J84RVAbKOLy2Vuusq2sC/Rjz3sC5LXsx5Y6vcwGr+NksF1/xt793Dgzdc1Jbb2fCfP/qgLdDkwHn88uyJIJMpmotjTahW7BU531ETnMcoHwBeH5tIEdITTffXsm9bX76pEeAy7stlZkfgRIGO9XCFcQNa4sDvrmMaaQ/KdvOGD9a6IK8hjk5l+8YTXBzWnij6KKfLDfjn9XCE2M7Pn/D7ke5gyIxejlsxQ7/7qXzzsqEIStykudTNrpxYf3FGMJgpgk4HI1ipHw7OlApd80Ertp4FnaVCmShMZbHaLPIX/Lc1Swiq4p5ff8krwhunjVPiNHsZuWAq3ZwhK8=
  - secure: xo3sZ1Uhh9KLpHgWMRx5nrhKGzwukXPCvMtSZ7v7Bm+eEuzw2fkAUwoZ4jQxr1S3Z7hCoasdnQpBIDG0xFzxU8eITpV/6PtmSlM0NVK8mLRRVAMdhSQYLPt7OPrEdd5ekgKL1FrDFEimcYHoRc2a3KY+c/qjcL+8hhJUA8B8bLHLpKAv1yGoxHHH+zhg1EiRYNEOlbtzKvY+pc32lxCz0/+lJN1t924qxlSQsPqz8JhLmbzM8IABcvO2AdieUSDgQ+BpA39Uei+l6GGI/2OLqZAjJsKIjKfizZuxWCPy6vqCJHesz7bxoKMbuJHlK/GqK8O6dK0sfDX/0Xw7Vx5KcFEEYiG3J3T+LZB4PCBOBJdtgh6NKiDXpvwSFtwf8BNmmcmZKa9tWYO3V8b74jmJmQt0j5vnioj5n3eEjP+ewp/B47pDKwtBYvAUlR2VQpl0gERAEYHYYjV+F1NNIQ5mkU9OS/PHL9CHFPuAat8mDIwReq7GOJ6JU7qvQ3K/KrGte1irHaHJNZq2raeLkx7N2uTqpH7s3ikv/NBM7M6tMacH3KNzoYEd4aSvLE/tPS0ZbUuMzkoRxEEWtD9iEWEY+LqJtu98JeXNlUl0QrXS4GDmDzs1tMuZAnnjCLsa3ot9lBtvvGgG2YsG3+0m1jYBhnN2JzWQQNabE8OWa9aVdMo=
